name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make init env=test
        
      - name: Run tests with coverage
        run: make test

      - name: Send coverage to Coveralls
        # You may pin to the exact commit or the version.
        # uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Path to lcov file
          path-to-lcov: /.coverage
          flag-name: Unit
